// Builds data/data.js from data/clips.json, data/signals.json and data/moments.json.
// The app reads window.CM_DATA instead of fetch(), so it also works from file://.
//
//   node tools/build-data.mjs
//
// For every clip it also records which thumbnail sizes exist on disk
// (thumb_sm / thumb_md / thumb), so the app never requests a missing image.

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const read = (name) => JSON.parse(readFileSync(join(root, 'data', name), 'utf8'));
const has = (rel) => typeof rel === 'string' && rel.length > 0 && existsSync(join(root, rel));

const clips = read('clips.json');
const signals = read('signals.json');
const moments = read('moments.json');

const problems = [];

for (const clip of clips) {
  const base = has(clip.thumb_path) ? clip.thumb_path : null;
  const sm = `assets/thumbs/sm/${clip.id}.jpg`;
  const md = `assets/thumbs/md/${clip.id}.jpg`;
  clip.thumb = base;
  clip.thumb_sm = has(sm) ? sm : base;
  clip.thumb_md = has(md) ? md : base;
  if (!base) problems.push(`clip ${clip.id}: thumbnail missing (${clip.thumb_path})`);
}

const clipIds = new Set(clips.map((c) => c.id));
const signalIds = new Set(signals.map((s) => s.id));
for (const m of moments) {
  if (!clipIds.has(m.clip_id)) problems.push(`moment ${m.id}: unknown clip ${m.clip_id}`);
  for (const id of m.signal_ids || []) {
    if (!signalIds.has(id)) problems.push(`moment ${m.id}: unknown signal ${id}`);
  }
  for (const p of ['tiktok', 'reels', 'shorts']) {
    const n = (m.drafts && m.drafts[p] && m.drafts[p].length) || 0;
    if (n !== 3) problems.push(`moment ${m.id}: ${n} ${p} drafts (expected 3)`);
  }
}

const payload = { clips, signals, moments };
const out =
  '/* Generated by tools/build-data.mjs from data/*.json. Do not edit by hand. */\n' +
  'window.CM_DATA = ' + JSON.stringify(payload) + ';\n';

writeFileSync(join(root, 'data', 'data.js'), out);

console.log(
  `data/data.js written: ${clips.length} clips, ${signals.length} signals, ${moments.length} moments ` +
  `(${(out.length / 1024).toFixed(1)} KB)`
);
if (problems.length) {
  console.warn('Warnings (the app degrades gracefully, but check these):');
  for (const p of problems) console.warn('  - ' + p);
}
